// DO NOT TOUCH. This file is automatically generated.
package main

import (
	"github.com/gin-gonic/gin"
	"github.com/nikel-api/nikel/common"
)

// getBuildings queries via the buildings endpoint
func getBuildings(c *gin.Context) {
	params, err := parsers.Courses.Parse([]byte(`{"filter": {"code": "ACMB01H3"}}`))

	if err != nil {
		panic(err)
	}

	var res []common.Course

	err = db.Where(params.FilterExp, params.FilterArgs).
		Offset(params.Offset).
		Limit(params.Limit).
		Order(params.Sort).
		Find(&res).Error

	if len(res) == 0 {
		sendEmptySuccess(c)
	} else {
		sendSuccess(c, res)
	}
}
