// DO NOT TOUCH. This file is automatically generated.
package main

import (
	"encoding/json"
	"github.com/gin-gonic/gin"
	"github.com/nikel-api/nikel/common"
	"math"
)

// getCourses queries via the courses endpoint
func getCourses(c *gin.Context) {
	offset := parseInt(c.Query("offset"), 0, math.MaxInt64, 0)
	limit := parseInt(c.Query("limit"), 1, common.TOPLIMIT, common.DEFAULTLIMIT)

	data := autoQuery(
		database.Courses,
		c.Request.URL.Query(),
		limit,
		offset,
	)

	res, _ := json.Marshal(data)
	var courses []common.Course
	json.Unmarshal(res, &courses)
	if len(courses) == 0 {
		sendEmptySuccess(c)
	} else {
		sendSuccess(c, courses)
	}
}
