// DO NOT TOUCH. This file is automatically generated.
package main

import (
	"encoding/json"
	"github.com/gin-gonic/gin"
	"github.com/nikel-api/nikel/common"
	"math"
)

// getExams queries via the exams endpoint
func getExams(c *gin.Context) {
	offset := parseInt(c.Query("offset"), 0, math.MaxInt64, 0)
	limit := parseInt(c.Query("limit"), 1, common.TOPLIMIT, common.DEFAULTLIMIT)

	data := autoQuery(
		database.Exams,
		c.Request.URL.Query(),
		limit,
		offset,
	)

	res, _ := json.Marshal(data)
	var exams []common.Exam
	json.Unmarshal(res, &exams)
	if len(exams) == 0 {
		sendEmptySuccess(c)
	} else {
		sendSuccess(c, exams)
	}
}
